### ISSUE TITLE
BF3 maps still have their skybox modified for default day time, after removing-delisting the mod from the server.

### ISSUE THREAD

**Issue by B-to480** [GramThanos/bf3-vu-day-night#4]
How do I revert any changes made by the day-night VU mod to my maps? I was testing my mods, I needed to remove the day-night mod, but that mod is still making changes to the skybox.

**Comment by GramThanos** [comment]
Just undo the installation steps.

1. Disable the mod by removing the `day-night` in your `ModList.txt` as a new row

2. Delete the mod's folder `\Server\Admin\Mods folder\day-night`

**Comment by B-to480** [comment]
Hi! thanks for responding! Well, I have done that, that is what I tried to communicate through the tittle of this issue, and it doesn't have effect on reverting the modificactions the day-night mod did. Another suggestion?

**Comment by GramThanos** [comment]
Did you restart the server? The mod doesn't change files on the server, it just controls the day-night cycle in the client side.

Maybe something was cached temporarily on the client side.

**Comment by B-to480** [comment]
Ok, found the problem, I didn't disabled the VU mod "Better BF3 visual" & "VEmanager", Any of those was, in some way, caching the changes from this mod. So yeah, thanks for helping!
